const data = {
  A: {
    COMIDA: 'Arroz',
    FRUTA: 'Avocado (abacate)',
    FLV: 'Avocado (abacate)',
    ANIMAL: 'Anta',
    CELEBRIDADE: 'Angélica',
    CARRO: 'Audi',
    CEP: 'Amazonas',
    COR: 'Azul',
    ESPORTE: 'Atletismo',
    'TIME ESPORTIVO': 'Arsenal',
    MSÉ: 'Amável',
    FILME: 'Antlers',
    'PROGRAMA DE TV': 'Antlers',
    SÉRIE: 'A Diarista',
    BANDA: 'A Banda Mais Bonita da Cidade',
    'INSTRUMENTO MUSICAL': 'Atabaque',
    MARCA: 'Antartica',
    'MEIO DE TRANSPORTE': 'Avião',
    PCH: 'Amigdala',
    ATOR: 'Angelina Jolie',
    FLOR: 'Acácia',
    OBJETO: 'Agulha',
    NOME: 'Amanda',
    NOME: 'Alcântara',
    PDA: 'Adam Warlock',
    'PERSONAGEM FICTÍCIO': 'Adam Warlock',
    ADJETIVO: 'Adorável',
    PROFISSÃO: 'Administrador',
  },
  B: {
    COMIDA: 'Bolo',
    FRUTA: 'Barbados Cherry (acerola)',
    FLV: 'Barbados Cherry (acerola)',
    ANIMAL: 'Bode',
    CELEBRIDADE: 'Bob Marley',
    CARRO: 'Bora',
    CEP: 'Bélgica',
    COR: 'Branco',
    ESPORTE: 'Basquete',
    'TIME ESPORTIVO': 'Barcelona',
    MSÉ: 'Burra',
    FILME: 'Bad Boys',
    'PROGRAMA DE TV': 'Bad Boys',
    SÉRIE: 'Band of Brothers',
    BANDA: 'Barão Vermelho',
    'INSTRUMENTO MUSICAL': 'Bateria',
    MARCA: 'Bic',
    'MEIO DE TRANSPORTE': 'Barco',
    PCH: 'Bunda',
    ATOR: 'Bruce Willis',
    FLOR: 'Bromélia',
    OBJETO: 'Bola',
    NOME: 'Bianca',
    NOME: 'Barbosa',
    PDA: 'Billy Batson',
    'PERSONAGEM FICTÍCIO': 'Billy Batson',
    ADJETIVO: 'Bonito',
    PROFISSÃO: 'Banqueiro',
  },
  C: {
    COMIDA: 'Chocolate',
    FRUTA: 'Cashew (caju)',
    FLV: 'Cashew (caju)',
    ANIMAL: 'Cavalo',
    CELEBRIDADE: 'Cazuza',
    CARRO: 'Corolla',
    CEP: 'Colombia',
    COR: 'Cinza',
    ESPORTE: 'Corrida',
    'TIME ESPORTIVO': 'Corinthans',
    MSÉ: 'Chata',
    FILME: 'Constantine',
    'PROGRAMA DE TV': 'Constantine',
    SÉRIE: 'Californication',
    BANDA: 'Capital Inicial',
    'INSTRUMENTO MUSICAL': 'Castanhola',
    MARCA: 'Colgate',
    'MEIO DE TRANSPORTE': 'CARRO',
    PCH: 'Clavícula',
    ATOR: 'Carolina Dieckmann',
    FLOR: 'Cacto',
    OBJETO: 'Copo',
    NOME: 'Camila',
    NOME: 'Campos',
    PDA: 'Capitã Marvel',
    'PERSONAGEM FICTÍCIO': 'Capitã Marvel',
    ADJETIVO: 'Corajoso',
    PROFISSÃO: 'Contador',
  },
  D: {
    COMIDA: 'Dendê',
    FRUTA: 'Dried Banana (banana-passa)',
    FLV: 'Dried Banana (banana-passa)',
    ANIMAL: 'Dromedário',
    CELEBRIDADE: 'Dado Dolabella',
    CARRO: 'Del Rey',
    CEP: 'Dinamarca',
    COR: 'Dourado',
    ESPORTE: 'Decatlo',
    'TIME ESPORTIVO': 'Dínamo',
    MSÉ: 'Doida',
    FILME: 'Duna',
    'PROGRAMA DE TV': 'Duna',
    SÉRIE: 'Dallas',
    BANDA: 'Deadfish',
    'INSTRUMENTO MUSICAL': 'Daxofone',
    MARCA: 'Disney',
    'MEIO DE TRANSPORTE': 'DDD',
    PCH: 'Dedos',
    ATOR: 'Dan Stulbach',
    FLOR: 'Dália',
    OBJETO: 'Dado',
    NOME: 'David',
    NOME: 'Dias',
    PDA: 'Dominó',
    'PERSONAGEM FICTÍCIO': 'Dominó',
    ADJETIVO: 'Dedicado',
    PROFISSÃO: 'Diagramador',
  },
  E: {
    COMIDA: 'Empada',
    FRUTA: 'Eggplant (berinjela)',
    FLV: 'Eggplant (berinjela)',
    ANIMAL: 'Escorpião',
    CELEBRIDADE: 'Eliana',
    CARRO: 'EcoSport',
    CEP: 'Espírito Santo',
    COR: 'Escarlate',
    ESPORTE: 'Esgrima',
    'TIME ESPORTIVO': 'Estudiante',
    MSÉ: 'Estudiosa',
    FILME: 'Elektra',
    'PROGRAMA DE TV': 'Elektra',
    SÉRIE: 'El Chavo Del Ocho (Chaves)',
    BANDA: 'Engenheiros do Hawaii',
    'INSTRUMENTO MUSICAL': 'Espineta',
    MARCA: 'Electrolux',
    'MEIO DE TRANSPORTE': 'Empilhadeira',
    PCH: 'Estômago',
    ATOR: 'Emma Stone',
    FLOR: 'Espirradeira',
    OBJETO: 'Escova',
    NOME: 'Emília',
    NOME: 'Escobar',
    PDA: 'Edward',
    'PERSONAGEM FICTÍCIO': 'Edward',
    ADJETIVO: 'Educado',
    PROFISSÃO: 'Edificador',
  },
  F: {
    COMIDA: 'Feijão',
    FRUTA: 'Fig (figo)',
    FLV: 'Fig (figo)',
    ANIMAL: 'Foca',
    CELEBRIDADE: 'Fergie',
    CARRO: 'Fusca',
    CEP: 'França',
    COR: 'Ferrugem',
    ESPORTE: 'Futebol',
    'TIME ESPORTIVO': 'Flamengo',
    MSÉ: 'Feia',
    FILME: 'Faroeste Caboclo',
    'PROGRAMA DE TV': 'Faroeste Caboclo',
    SÉRIE: 'Faking It',
    BANDA: 'Fresno',
    'INSTRUMENTO MUSICAL': 'Flauta',
    MARCA: 'Ford',
    'MEIO DE TRANSPORTE': 'Foguete',
    PCH: 'Fígado',
    ATOR: 'Fernanda Lima',
    FLOR: 'Flor-de-Lis',
    OBJETO: 'Faca',
    NOME: 'Fernando',
    NOME: 'Fernandes',
    PDA: 'Flynn Ryder',
    'PERSONAGEM FICTÍCIO': 'Flynn Ryder',
    ADJETIVO: 'Formoso',
    PROFISSÃO: 'Fuzileiro',
  },
  G: {
    COMIDA: 'Gelatina',
    FRUTA: 'Guava (goiaba)',
    FLV: 'Guava (goiaba)',
    ANIMAL: 'Gato',
    CELEBRIDADE: 'Glória Maria',
    CARRO: 'Gol',
    CEP: 'Gales',
    COR: 'Grená',
    ESPORTE: 'Ginástica',
    'TIME ESPORTIVO': 'Goiás',
    MSÉ: 'Gorda',
    FILME: 'Garotas Selvagens',
    'PROGRAMA DE TV': 'Garotas Selvagens',
    SÉRIE: 'Game of Thrones',
    BANDA: 'Glória',
    'INSTRUMENTO MUSICAL': 'Gongo',
    MARCA: 'Gillete',
    'MEIO DE TRANSPORTE': 'Guincho',
    PCH: 'Garganta',
    ATOR: 'Grant Gustin',
    FLOR: 'Gardênia',
    OBJETO: 'Gaiola',
    NOME: 'Gabrielly',
    NOME: 'Galvão',
    PDA: 'Gaston',
    'PERSONAGEM FICTÍCIO': 'Gaston',
    ADJETIVO: 'Generoso',
    PROFISSÃO: 'Goleiro',
  },
  H: {
    COMIDA: 'Húmus',
    FRUTA: 'HHH',
    FLV: 'HHH',
    ANIMAL: 'Hipopótamo',
    CELEBRIDADE: 'Harry Styles',
    CARRO: 'HB20',
    CEP: 'Havaí',
    COR: 'Herbal',
    ESPORTE: 'Hipismo',
    'TIME ESPORTIVO': 'Horizonte',
    MSÉ: 'Honesta',
    FILME: 'Homem de Aço',
    'PROGRAMA DE TV': 'Homem de Aço',
    SÉRIE: 'Homeland',
    BANDA: 'Hori',
    'INSTRUMENTO MUSICAL': 'Harpa',
    MARCA: 'H&M',
    'MEIO DE TRANSPORTE': 'Helicóptero',
    PCH: 'Hipotálamo',
    ATOR: 'Hailee Steinfield',
    FLOR: 'Hibisco',
    OBJETO: 'Holofote',
    NOME: 'Hugo',
    NOME: 'Holanda',
    PDA: 'Harry Potter',
    'PERSONAGEM FICTÍCIO': 'Harry Potter',
    ADJETIVO: 'Honesto',
    PROFISSÃO: 'Historiador',
  },
  I: {
    COMIDA: 'Iogurte',
    FRUTA: 'III',
    FLV: 'III',
    ANIMAL: 'Iguana',
    CELEBRIDADE: 'Ingrid Guimarães',
    CARRO: 'i30',
    CEP: 'Índia',
    COR: 'Índigo',
    ESPORTE: 'Iatismo',
    'TIME ESPORTIVO': 'Internazionale',
    MSÉ: 'Inteligente',
    FILME: 'Interestellar',
    'PROGRAMA DE TV': 'Interestellar',
    SÉRIE: "I'm Not Okay with This |",
    BANDA: 'Ira',
    'INSTRUMENTO MUSICAL': 'Inúbia',
    MARCA: 'Intel',
    'MEIO DE TRANSPORTE': 'III',
    PCH: 'Intestino',
    ATOR: 'Ingrid Guimarães',
    FLOR: 'Ipê',
    OBJETO: 'Imã',
    NOME: 'Irma',
    NOME: 'Izidoro',
    PDA: 'Indiana Jones',
    'PERSONAGEM FICTÍCIO': 'Indiana Jones',
    ADJETIVO: 'Íntegro',
    PROFISSÃO: 'Ilustrador',
  },
  J: {
    COMIDA: 'Jaca',
    FRUTA: 'Jackfruit (jaca)',
    FLV: 'Jackfruit (jaca)',
    ANIMAL: 'Jabuti',
    CELEBRIDADE: 'José de Abreu',
    CARRO: 'Jeep',
    CEP: 'Jamaica',
    COR: 'Jade',
    ESPORTE: 'Judô',
    'TIME ESPORTIVO': 'Juventus',
    MSÉ: 'Joia',
    FILME: 'Jackass',
    'PROGRAMA DE TV': 'Jackass',
    SÉRIE: 'Jack Ryan',
    BANDA: 'Júpiter Maçã',
    'INSTRUMENTO MUSICAL': 'JJJ',
    MARCA: 'Jeep',
    'MEIO DE TRANSPORTE': 'Jetski',
    PCH: 'Joelho',
    ATOR: 'Justin Timberlake',
    FLOR: 'Jasmin',
    OBJETO: 'Jarro',
    NOME: 'Joana',
    NOME: 'Juarez',
    PDA: 'Junniper Lee',
    'PERSONAGEM FICTÍCIO': 'Junniper Lee',
    ADJETIVO: 'Justo',
    PROFISSÃO: 'Jardineiro',
  },
  K: {
    COMIDA: 'Kiwi',
    FRUTA: 'Kiwifruit (kiwi)',
    FLV: 'Kiwifruit (kiwi)',
    ANIMAL: 'KKK',
    CELEBRIDADE: 'Ke$ha',
    CARRO: 'Kombi',
    CEP: 'Kansas',
    COR: 'KKK',
    ESPORTE: 'Karatê',
    'TIME ESPORTIVO': 'KKK',
    MSÉ: 'KKK',
    FILME: 'Karate Kid',
    'PROGRAMA DE TV': 'Karate Kid',
    SÉRIE: 'Kaos',
    BANDA: 'KC. and The Sunshine Band',
    'INSTRUMENTO MUSICAL': 'KKK',
    MARCA: 'Kalunga',
    'MEIO DE TRANSPORTE': 'Kart',
    PCH: 'KKK',
    ATOR: 'Katie Holmes',
    FLOR: 'KKK',
    OBJETO: '',
    NOME: 'Kátia',
    NOME: 'Kaspar',
    PDA: 'Kronk',
    'PERSONAGEM FICTÍCIO': 'Kronk',
    ADJETIVO: 'KKK',
    PROFISSÃO: 'Karateca',
  },
  L: {
    COMIDA: 'Leite',
    FRUTA: 'Lemon/Lime (limão)',
    FLV: 'Lemon/Lime (limão)',
    ANIMAL: 'Leão',
    CELEBRIDADE: 'Liam Payne',
    CARRO: 'Land Rover',
    CEP: 'Londres',
    COR: 'Laranja',
    ESPORTE: 'Lacrosse',
    'TIME ESPORTIVO': 'Liverpool',
    MSÉ: 'Linda',
    FILME: 'Lolita',
    'PROGRAMA DE TV': 'Lolita',
    SÉRIE: 'La Casa de Papel',
    BANDA: 'Legião Urbana',
    'INSTRUMENTO MUSICAL': 'Lira',
    MARCA: 'Lacoste',
    'MEIO DE TRANSPORTE': 'Locomotiva',
    PCH: 'Laringe',
    ATOR: "Lupitaa Nyong'o",
    FLOR: 'Lírio',
    OBJETO: 'Luvas',
    NOME: 'Luana',
    NOME: 'Lopes',
    PDA: 'Linguado',
    'PERSONAGEM FICTÍCIO': 'Linguado',
    ADJETIVO: 'Lúcido',
    PROFISSÃO: 'Lanterninha',
  },
  M: {
    COMIDA: 'Mandioca',
    FRUTA: 'Mango (manga)',
    FLV: 'Mango (manga)',
    ANIMAL: 'Morcego',
    CELEBRIDADE: 'Madonna',
    CARRO: 'Mustang',
    CEP: 'Mônaco',
    COR: 'Marrom',
    ESPORTE: 'Muay-Thay',
    'TIME ESPORTIVO': 'Milan',
    MSÉ: 'Maravilhosa',
    FILME: 'Mulher-Maravilha',
    'PROGRAMA DE TV': 'Mulher-Maravilha',
    SÉRIE: 'MacGyver',
    BANDA: 'Mamomas Assassinas',
    'INSTRUMENTO MUSICAL': 'Marimba',
    MARCA: 'Motorola',
    'MEIO DE TRANSPORTE': 'Moto',
    PCH: 'Mãos',
    ATOR: 'Misha Collins',
    FLOR: 'Madressilva',
    OBJETO: 'Maquiagem',
    NOME: 'Mariana',
    NOME: 'Machado',
    PDA: 'Mulher-Maravilha',
    'PERSONAGEM FICTÍCIO': 'Mulher-Maravilha',
    ADJETIVO: 'Maduro',
    PROFISSÃO: 'Madereiro',
  },
  N: {
    COMIDA: 'Nachos',
    FRUTA: 'NNN',
    FLV: 'NNN',
    ANIMAL: 'Naja',
    CELEBRIDADE: 'Naldo Benny',
    CARRO: 'Nivus',
    CEP: 'Noruega',
    COR: 'Naval',
    ESPORTE: 'Natação',
    'TIME ESPORTIVO': 'Náutico',
    MSÉ: 'Natual',
    FILME: 'Nanny McPhee',
    'PROGRAMA DE TV': 'Nanny McPhee',
    SÉRIE: 'Narcos',
    BANDA: 'Natiruts',
    'INSTRUMENTO MUSICAL': 'NNN',
    MARCA: 'Nike',
    'MEIO DE TRANSPORTE': 'Navio',
    PCH: 'Nariz',
    ATOR: 'Nicette Bruno',
    FLOR: 'Narciso',
    OBJETO: 'Navalha',
    NOME: 'Nathan',
    NOME: 'Novaes',
    PDA: 'Nemo',
    'PERSONAGEM FICTÍCIO': 'Nemo',
    ADJETIVO: 'Nova',
    PROFISSÃO: 'Narrador',
  },
  O: {
    COMIDA: 'Ovo',
    FRUTA: 'Orange (laranja)',
    FLV: 'Orange (laranja)',
    ANIMAL: 'Ovelha',
    CELEBRIDADE: 'Oprah',
    CARRO: 'Opala',
    CEP: 'Orlando',
    COR: 'Ocre',
    ESPORTE: 'OOO',
    'TIME ESPORTIVO': 'Orlando City',
    MSÉ: 'Ótima',
    FILME: 'Os Incríveis',
    'PROGRAMA DE TV': 'Os Incríveis',
    SÉRIE: 'Once Upon a Time',
    BANDA: 'Onze:20',
    'INSTRUMENTO MUSICAL': 'Oboé',
    MARCA: 'Outback',
    'MEIO DE TRANSPORTE': 'Ônibus',
    PCH: 'Olhos',
    ATOR: 'Orlando Bloom',
    FLOR: 'Orquídea',
    OBJETO: 'Óculos',
    NOME: 'Osvaldo',
    NOME: 'Oliveira',
    PDA: 'Olivia Palito',
    'PERSONAGEM FICTÍCIO': 'Olivia Palito',
    ADJETIVO: 'Otimista',
    PROFISSÃO: 'Oftalmologista',
  },
  P: {
    COMIDA: 'Patê',
    FRUTA: 'Papaya (mamão)',
    FLV: 'Papaya (mamão)',
    ANIMAL: 'Pato',
    CELEBRIDADE: 'Paulo Gustavo',
    CARRO: 'Porsche',
    CEP: 'Paris',
    COR: 'Preto',
    ESPORTE: 'Patinação',
    'TIME ESPORTIVO': 'Palmeiras',
    MSÉ: 'Pequena',
    FILME: 'Percy Jackson e o Ladrão de Raios',
    'PROGRAMA DE TV': 'Percy Jackson e o Ladrão de Raios',
    SÉRIE: 'Pan Am',
    BANDA: 'Pato Fu',
    'INSTRUMENTO MUSICAL': 'Prato',
    MARCA: 'Panasonic',
    'MEIO DE TRANSPORTE': 'Patinete',
    PCH: 'Pele',
    ATOR: 'Penélope Cruz',
    FLOR: 'Papoula',
    OBJETO: 'Pedra',
    NOME: 'Pâmela',
    NOME: 'Pacheco',
    PDA: 'Pepper Potts',
    'PERSONAGEM FICTÍCIO': 'Pepper Potts',
    ADJETIVO: 'Prático',
    PROFISSÃO: 'Porteiro',
  },
  Q: {
    COMIDA: 'Queijo',
    FRUTA: 'Quince (marmelo)',
    FLV: 'Quince (marmelo)',
    ANIMAL: 'Quero-Quero',
    CELEBRIDADE: 'Queen Latifah',
    CARRO: 'Quantum',
    CEP: 'Quênia',
    COR: 'QQQ',
    ESPORTE: '',
    'TIME ESPORTIVO': 'QQQ',
    MSÉ: 'Querida',
    FILME: 'Querido John',
    'PROGRAMA DE TV': 'Querido John',
    SÉRIE: 'Queer Eye',
    BANDA: 'Queen',
    'INSTRUMENTO MUSICAL': 'Quena',
    MARCA: 'Quero',
    'MEIO DE TRANSPORTE': 'QQQ',
    PCH: 'Queixo',
    ATOR: 'Queen Latifah',
    FLOR: 'Quaresmeira',
    OBJETO: 'Quadro',
    NOME: 'Quésia',
    NOME: 'Quaresma',
    PDA: 'Quinzinho',
    'PERSONAGEM FICTÍCIO': 'Quinzinho',
    ADJETIVO: 'Querido',
    PROFISSÃO: 'Queijeiro',
  },
  R: {
    COMIDA: 'Rúcula',
    FRUTA: 'Raspberry (framboesa)',
    FLV: 'Raspberry (framboesa)',
    ANIMAL: 'Rato',
    CELEBRIDADE: 'Rihanna',
    CARRO: 'Ranger Rover',
    CEP: 'Rondônia',
    COR: 'Rosa',
    ESPORTE: 'Rugby',
    'TIME ESPORTIVO': 'Real Madrid',
    MSÉ: 'Ridícula',
    FILME: 'Riquinho',
    'PROGRAMA DE TV': 'Riquinho',
    SÉRIE: 'Ragnarok',
    BANDA: 'Restart',
    'INSTRUMENTO MUSICAL': 'Reco-Reco',
    MARCA: 'Renault',
    'MEIO DE TRANSPORTE': 'RRR',
    PCH: 'Rim',
    ATOR: 'Rihanna',
    FLOR: 'Rosa',
    OBJETO: 'Régua',
    NOME: 'Ronaldo',
    NOME: 'Ramalho',
    PDA: 'Rachel Green',
    'PERSONAGEM FICTÍCIO': 'Rachel Green',
    ADJETIVO: 'Rápido',
    PROFISSÃO: 'Roteirista',
  },
  S: {
    COMIDA: 'Sorvete',
    FRUTA: 'Strawberry (morango)',
    FLV: 'Strawberry (morango)',
    ANIMAL: 'Sapo',
    CELEBRIDADE: 'Suzana Vieira',
    CARRO: 'Santana',
    CEP: 'Stockton',
    COR: 'Salmão',
    ESPORTE: 'Surf',
    'TIME ESPORTIVO': 'São Paulo',
    MSÉ: 'Santa',
    FILME: 'Sherlock Holmes',
    'PROGRAMA DE TV': 'Sherlock Holmes',
    SÉRIE: 'Sabrina: Aprendiz de Feiticeira',
    BANDA: 'Scorpions',
    'INSTRUMENTO MUSICAL': 'Sino',
    MARCA: 'Sony |Stihl',
    'MEIO DE TRANSPORTE': 'Submarino',
    PCH: 'Sovaco',
    ATOR: 'Sandra Bullock',
    FLOR: 'Sálvia',
    OBJETO: 'Sapato',
    NOME: 'Samanta',
    NOME: 'Santos',
    PDA: 'Soldado Invernal',
    'PERSONAGEM FICTÍCIO': 'Soldado Invernal',
    ADJETIVO: 'Sábio',
    PROFISSÃO: 'Segurança',
  },
  T: {
    COMIDA: 'Tucupi',
    FRUTA: 'Tangerine (tangerina)',
    FLV: 'Tangerine (tangerina)',
    ANIMAL: 'Texugo',
    CELEBRIDADE: 'Tessa Thompson',
    CARRO: 'Tucson',
    CEP: 'Teerã',
    COR: 'Turquesa',
    ESPORTE: 'Tênis',
    'TIME ESPORTIVO': 'Tottenham',
    MSÉ: 'Trabalhadora',
    FILME: 'Tá Chovendo Hambúrguer',
    'PROGRAMA DE TV': 'Tá Chovendo Hambúrguer',
    SÉRIE: 'Teen Wolf',
    BANDA: 'Titãs',
    'INSTRUMENTO MUSICAL': 'Tambor',
    MARCA: 'Topper',
    'MEIO DE TRANSPORTE': 'Táxi',
    PCH: 'Tornozelo',
    ATOR: 'Tessa Thompson',
    FLOR: 'Tulipa',
    OBJETO: 'Tesoura',
    NOME: 'Tânia',
    NOME: 'Teixeira',
    PDA: 'Thor',
    'PERSONAGEM FICTÍCIO': 'Thor',
    ADJETIVO: 'Terno',
    PROFISSÃO: 'Tabelião',
  },
  U: {
    COMIDA: 'Uva',
    FRUTA: 'UUU',
    FLV: 'UUU',
    ANIMAL: 'Urso',
    CELEBRIDADE: 'Usher',
    CARRO: 'Uno',
    CEP: 'Utah',
    COR: 'Urucum',
    ESPORTE: 'UUU',
    'TIME ESPORTIVO': 'UUU',
    MSÉ: 'Útil',
    FILME: 'Uma Prova de Amor',
    'PROGRAMA DE TV': 'Uma Prova de Amor',
    SÉRIE: 'Ugly Betty',
    BANDA: 'Ultraje a Rigor',
    'INSTRUMENTO MUSICAL': 'Ukulelê',
    MARCA: 'Universal',
    'MEIO DE TRANSPORTE': 'UUU',
    PCH: 'Unha',
    ATOR: 'Uriel Del Toro',
    FLOR: 'Unha de Gato',
    OBJETO: 'Urna',
    NOME: 'Ulisses',
    NOME: 'Uchoa',
    PDA: 'Uni',
    'PERSONAGEM FICTÍCIO': 'Uni',
    ADJETIVO: 'Único',
    PROFISSÃO: 'Urbanista',
  },
  V: {
    COMIDA: 'Vatapá',
    FRUTA: 'VVV',
    FLV: 'VVV',
    ANIMAL: 'Vespa',
    CELEBRIDADE: 'Vanessa da Mata',
    CARRO: 'Vectra',
    CEP: 'Venezuela',
    COR: 'Violeta',
    ESPORTE: 'Vôlei',
    'TIME ESPORTIVO': 'Vasco da Gama',
    MSÉ: 'Veloz',
    FILME: 'Valente',
    'PROGRAMA DE TV': 'Valente',
    SÉRIE: 'Van Helsing',
    BANDA: 'Vespas Mandarinas',
    'INSTRUMENTO MUSICAL': 'Violão',
    MARCA: 'Vans',
    'MEIO DE TRANSPORTE': 'Veleiro',
    PCH: 'Veias',
    ATOR: 'Viola Davis',
    FLOR: 'Violeta',
    OBJETO: 'Ventilador',
    NOME: 'Vanessa',
    NOME: 'Venâncio',
    PDA: 'Venom',
    'PERSONAGEM FICTÍCIO': 'Venom',
    ADJETIVO: 'Valoroso',
    PROFISSÃO: 'Vendedor',
  },
  W: {
    COMIDA: 'Waffle',
    FRUTA: 'Watermelon (melancia)',
    FLV: 'Watermelon (melancia)',
    ANIMAL: 'WWW',
    CELEBRIDADE: 'Wesley Safadão',
    CARRO: 'WRV',
    CEP: 'Washington',
    COR: 'WWW',
    ESPORTE: 'Windsurf',
    'TIME ESPORTIVO': 'WWW',
    MSÉ: 'WWW',
    FILME: 'Wendy Wu - A Garota Kung Fu',
    'PROGRAMA DE TV': 'Wendy Wu - A Garota Kung Fu',
    SÉRIE: 'WandaVision',
    BANDA: 'WWW',
    'INSTRUMENTO MUSICAL': 'WWW',
    MARCA: 'Warner',
    'MEIO DE TRANSPORTE': 'WWW',
    PCH: 'WWW',
    ATOR: 'Wesley Snipes',
    FLOR: 'WWW',
    OBJETO: 'Webcam',
    NOME: 'Wellington',
    NOME: 'Walker',
    PDA: 'Wilma',
    'PERSONAGEM FICTÍCIO': 'Wilma',
    ADJETIVO: 'WWW',
    PROFISSÃO: 'Web Designer',
  },
  X: {
    COMIDA: 'Xixá',
    FRUTA: 'XXX',
    FLV: 'XXX',
    ANIMAL: 'Xexéu (ave)',
    CELEBRIDADE: 'Xuxa',
    CARRO: 'Xsara',
    CEP: 'Xexéu',
    COR: 'XXX',
    ESPORTE: 'XXX',
    'TIME ESPORTIVO': 'XXX',
    MSÉ: 'XXX',
    FILME: 'X-Men',
    'PROGRAMA DE TV': 'X-Men',
    SÉRIE: 'Xena: A Princesa Guerreira',
    BANDA: 'XXX',
    'INSTRUMENTO MUSICAL': 'Xilofone',
    MARCA: 'X-Games',
    'MEIO DE TRANSPORTE': 'XXX',
    PCH: 'XXX',
    ATOR: 'Xuxa',
    FLOR: 'XXX',
    OBJETO: 'Xícara',
    NOME: 'Xavier',
    NOME: 'Xavier',
    PDA: 'Xaveco',
    'PERSONAGEM FICTÍCIO': 'Xaveco',
    ADJETIVO: 'Xavecador',
    PROFISSÃO: 'Xilógrafo',
  },
  Y: {
    COMIDA: 'Yakisoba',
    FRUTA: 'YYY',
    FLV: 'YYY',
    ANIMAL: 'YYY',
    CELEBRIDADE: 'Yuri Fernandes',
    CARRO: 'Yaris',
    CEP: 'Yale',
    COR: 'YYY',
    ESPORTE: 'YYY',
    'TIME ESPORTIVO': 'YYY',
    MSÉ: 'YYY',
    FILME: 'Yellowbird',
    'PROGRAMA DE TV': 'Yellowbird',
    SÉRIE: 'YYY',
    BANDA: 'YYY',
    'INSTRUMENTO MUSICAL': 'YYY',
    MARCA: 'Yahoo',
    'MEIO DE TRANSPORTE': 'YYY',
    PCH: 'YYY',
    ATOR: 'Yanna Lavigne',
    FLOR: 'YYY',
    OBJETO: 'YYY',
    NOME: 'Yuri',
    NOME: 'Young',
    PDA: 'Ysma',
    'PERSONAGEM FICTÍCIO': 'Ysma',
    ADJETIVO: 'YYY',
    PROFISSÃO: 'Youtuber',
  },
  Z: {
    COMIDA: 'Zoni',
    FRUTA: 'ZZZ',
    FLV: 'ZZZ',
    ANIMAL: 'Zebra',
    CELEBRIDADE: 'Zac Efron',
    CARRO: 'Zetta',
    CEP: 'Zimbábue',
    COR: 'ZZZ',
    ESPORTE: 'ZZZ',
    'TIME ESPORTIVO': 'Zenit',
    MSÉ: 'Zelosa',
    FILME: 'Zorro',
    'PROGRAMA DE TV': 'Zorro',
    SÉRIE: '',
    BANDA: 'Zomboy',
    'INSTRUMENTO MUSICAL': 'Zabumba',
    MARCA: 'Zara',
    'MEIO DE TRANSPORTE': 'Zeppelin',
    PCH: 'Zigoto',
    ATOR: 'Zoe Deschannel',
    FLOR: 'ZZZ',
    OBJETO: 'Zíper',
    NOME: 'Zélia',
    NOME: 'Zabel',
    PDA: 'Zulema',
    'PERSONAGEM FICTÍCIO': 'Zulema',
    ADJETIVO: 'Zeloso',
    PROFISSÃO: 'Zelador',
  },
};
